#: kivy 1.9.1

<GameScreen>
    name: "game"

    Image:
        source: "images/background.jpg"
        keep_ratio: False
        allow_stretch: True

    # This is the GameScreen layout, for now a Grid
    GridLayout:
        id: layout
        col_default_width: 20
        row_default_height: 40
        row_force_default: True

        cols: 3
        rows: 3

        Label:
            id: server_name
            #text: 'Server Name (replace with server name from server_name.text'


